version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/dashboard.olsera.co.id/
    # overwrite: yes
hooks:
  BeforeInstall:
    - location: codedeploy/beforeInstall
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/afterInstall
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: codedeploy/start_server
      timeout: 300
      runas: root

